/* Neo Wang
 * March 24, 2026
 * Displays a GUI JFrame information menu for the user to add a device 
 */
package com.neo.techfortommorowprogram.ui;

import com.neo.techfortommorowprogram.domain.TechDevice;
import javax.swing.JOptionPane;

/**
 *
 * @author L0W-R1SE
 */
public class DeviceCreater extends javax.swing.JFrame {

    /**
     * Creates new form AddDevice
     */
    private TechDevice newDevice; //globally creates the new device object so it can be accessed from a proper an accessor (getter)
    
    public DeviceCreater() {
        initComponents();
    }
    
    /**
     * Accessor for the new device object created by the user
     * @return the new TechDevice object
     */
    public TechDevice getDevice(){
        return newDevice; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceTypeBtnGroup = new javax.swing.ButtonGroup();
        statusBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idNumTxt = new javax.swing.JTextField();
        brandModelTxt = new javax.swing.JTextField();
        replacementValueTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        laptopBtn = new javax.swing.JRadioButton();
        tabletBtn = new javax.swing.JRadioButton();
        roboticsKitBtn = new javax.swing.JRadioButton();
        accessoryBtn = new javax.swing.JRadioButton();
        statusAvailableBtn = new javax.swing.JRadioButton();
        statusBorrowedBtn = new javax.swing.JRadioButton();
        statusUnderRepairBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Information Form");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID Code:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Device Type:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Brand Model:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Status:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Replacement Value:    $");

        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        deviceTypeBtnGroup.add(laptopBtn);
        laptopBtn.setText("Laptop");
        laptopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laptopBtnActionPerformed(evt);
            }
        });

        deviceTypeBtnGroup.add(tabletBtn);
        tabletBtn.setText("Tablet");

        deviceTypeBtnGroup.add(roboticsKitBtn);
        roboticsKitBtn.setText("Robotics Kit");
        roboticsKitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roboticsKitBtnActionPerformed(evt);
            }
        });

        deviceTypeBtnGroup.add(accessoryBtn);
        accessoryBtn.setText("Accessory");

        statusBtnGroup.add(statusAvailableBtn);
        statusAvailableBtn.setText("Available");

        statusBtnGroup.add(statusBorrowedBtn);
        statusBorrowedBtn.setText("Borrowed");

        statusBtnGroup.add(statusUnderRepairBtn);
        statusUnderRepairBtn.setText("Under Repair");

        jLabel7.setText("Format: 6-digit alphanumeric code ");

        jLabel8.setText("Based on device type. Ex. LT0021 for Laptop");

        jLabel9.setText("Full brand + model name. Ex Dell Inspirion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brandModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(statusAvailableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusBorrowedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusUnderRepairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(replacementValueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(laptopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roboticsKitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tabletBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(accessoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(laptopBtn)
                            .addComponent(tabletBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roboticsKitBtn)
                            .addComponent(accessoryBtn))
                        .addGap(14, 14, 14)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(brandModelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statusAvailableBtn)
                    .addComponent(statusBorrowedBtn)
                    .addComponent(statusUnderRepairBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(replacementValueTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Stores and error checks all user inputs before instantiating a new TechDevice object and adding it into the TechDevice array list
     * @param evt When the button is pressed
     */
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String idCode = idNumTxt.getText(); //stores the user input for the ID number of the new device
        boolean validInfo = true; //tracts if the user has entered all the info correctly. Assumes the user has unless shown otherwise 
        //stores and error checks the new device's device type
        String deviceType = "";
        //the radio buttons are in a button group, making sure the user can only pick one device type button at once
        if(laptopBtn.isSelected()){ //matches the device type to which every radio button the user picked. 
            deviceType = "Laptop"; //matches the device type to which every radio button the user picked. 
        }else if(tabletBtn.isSelected()){
            deviceType = "Tablet";
        }else if(roboticsKitBtn.isSelected()){
            deviceType = "Robotics Kit";
        }else if(accessoryBtn.isSelected()){
            deviceType = "Accessory";
        }else{ //if the user did not pick any device type option
            JOptionPane.showMessageDialog(null, "Please select a Device Type", "Error", JOptionPane.ERROR_MESSAGE); //displays error message telling user to select a device type
            validInfo = false; //sets validInfo boolean checker to false
        }
        
        //stores and error checks the brand model of the new device 
        String brandModel = brandModelTxt.getText();
        if(brandModel.equals("")){ //if the user entered nothing for the brand model
            validInfo = false; //sets validInfo boolean checker to false
            JOptionPane.showMessageDialog(null, "Please enter a Brand Model", "Error", JOptionPane.ERROR_MESSAGE); //displays error message
        }
        
        //stores and error checks the status of the new device
        String status = "";
        //the radio buttons are in a button group, making sure the user can only pick one status type button at once
        if(statusAvailableBtn.isSelected()){ //matches the device type to which every radio button the user picked. 
            status = "Available"; //matches the device type to which every radio button the user picked. 
        }else if(statusBorrowedBtn.isSelected()){
            status = "Borrowed";
        }else if(statusUnderRepairBtn.isSelected()){
            status = "Under Repair";
        }else{ //if the user did not pick any device type option
            JOptionPane.showMessageDialog(null, "Please select a Device Status", "Error", JOptionPane.ERROR_MESSAGE); //displays error message
            validInfo = false; //sets validInfo boolean checker to false
        }
        
        //stores and error checks replacement value of the new device
        String sReplacementValue = replacementValueTxt.getText(); 
        double replacementValue = 0;
        try{ //try and catch any NumberFormatExceptions when parsing a double out of the users replacement value input
            replacementValue = Double.parseDouble(sReplacementValue); //trys to parse a double
        }catch(NumberFormatException e){ //detects a number format exception, preventing a code crash
            JOptionPane.showMessageDialog(null, "Please enter a valid replacement cost.", "Error", JOptionPane.ERROR_MESSAGE); //displays error message
            validInfo = false; //sets validInfo boolean checker to false
        }
        
        //further error checks it the ID number the user entered mathces the formats for the type of device, and if it is 6 digits 
        //Laptop has to start with LT, Tablet: TB, Robotics Kit: RK, Accessory: AC
        if(idCode.length() != 6){ //if the ID code is not 6 digits
            validInfo = false;  //sets validInfo boolean checker to false
            JOptionPane.showMessageDialog(null, "ID Number not 6 digits", "Error", JOptionPane.ERROR_MESSAGE); //displays error message
        }else if(deviceType.equals("Laptop") && !idCode.substring(0,2).equals("LT")){ //error checks type mismatch for ID Code
            validInfo = false; //sets validInfo boolean checker to false
            JOptionPane.showMessageDialog(null, "\nID Code Starter: \"" + idCode.substring(0,2) + 
                    "\"\ndoes not match standard Laptop Id Prefix: \"LT\"", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(deviceType.equals("Tablet") && !idCode.substring(0,2).equals("TB")){ //error checks type mismatch for ID Code
            validInfo = false; //sets validInfo boolean checker to false
            JOptionPane.showMessageDialog(null, "\nID Code Starter: \"" + idCode.substring(0,2) + 
                    "\"\ndoes not match standard Tablet Id Prefix: \"TB\"", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(deviceType.equals("Robotics Kit") && !idCode.substring(0,2).equals("RK")){ //error checks type mismatch for ID Code
            validInfo = false; //sets validInfo boolean checker to false
            JOptionPane.showMessageDialog(null, "\nID Code Starter: \"" + idCode.substring(0,2) + 
                    "\"\ndoes not match standard Robotics Kit Id Prefix: \"RK\"", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(deviceType.equals("Accessory") && !idCode.substring(0,2).equals("AC")){ //error checks type mismatch for ID Code
            validInfo = false; //sets validInfo boolean checker to false
            JOptionPane.showMessageDialog(null, "\nID Code Starter: \"" + idCode.substring(0,2) + 
                    "\"\ndoes not match standard Accessory Id Prefix: \"AC\"", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

        if(validInfo){ //if the validInfo boolean check is true (user did not fail a single error check)
            newDevice = new TechDevice(idCode, deviceType, brandModel, status, replacementValue); //instantitaes a new object
            this.dispose(); //closes the JFrame menu
        }
        
        
        
        
        
        
    }//GEN-LAST:event_submitBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose(); //if the user presses the cancel button, closes the JFrame
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void laptopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laptopBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laptopBtnActionPerformed

    private void roboticsKitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roboticsKitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roboticsKitBtnActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accessoryBtn;
    private javax.swing.JTextField brandModelTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.ButtonGroup deviceTypeBtnGroup;
    private javax.swing.JTextField idNumTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton laptopBtn;
    private javax.swing.JTextField replacementValueTxt;
    private javax.swing.JRadioButton roboticsKitBtn;
    private javax.swing.JRadioButton statusAvailableBtn;
    private javax.swing.JRadioButton statusBorrowedBtn;
    private javax.swing.ButtonGroup statusBtnGroup;
    private javax.swing.JRadioButton statusUnderRepairBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JRadioButton tabletBtn;
    // End of variables declaration//GEN-END:variables
}
